Improve documentation
hacf-fr/meteofrance-api pull request #33
Opened 2020-10-03 05:43 UTC by oncleben31

Contribute to #18 by applying good practices of https://cjolowicz.github.io/posts/hypermodern-python-05-documentation/:

- Review of the docstrings
- Use darglint in test suite to validate docstrings against function signatures

2020-10-06 15:18 UTC, Quentame reviewed
Half of the review for now.
Will continue.

2020-10-11 13:51 UTC, Quentame requested changes
Some words to correct

2020-10-11 13:51 UTC, Quentame commented on CONTRIBUTING.rst
> +Even if you are not a developer, you can probably help to report some bugs, share
```suggestion
Even if you are not a developer, you can help to report some bugs, share
```
?

2020-10-11 13:51 UTC, Quentame commented on README.rst
> +* Accéder aux prévisions météorologiques horraires ou quotidiennes.
```suggestion
* Accéder aux prévisions météorologiques horaires ou quotidiennes.
```

2020-10-11 13:51 UTC, Quentame commented on README.rst
> +* Accéder aux alertes météo pour chaque département français et l'Andorre. Deux
```suggestion
* Accéder aux alertes météo pour chaque département français et d'Andorre. Deux
```

2020-10-11 13:51 UTC, Quentame commented on README.rst
> +Descritption
```suggestion
Description
```

2020-10-11 13:51 UTC, Quentame commented on README.rst
> +Déscription
```suggestion
Description
```

2020-10-11 13:51 UTC, Quentame commented on README.rst
> +used by the official moblie applications.
```suggestion
used by the official mobile applications.
```

2020-10-11 13:51 UTC, Quentame commented on README.rst
> +Météo-France utilisée par les applications moblies officielles.
```suggestion
Météo-France utilisée par les applications mobiles officielles.
```

2020-10-11 13:51 UTC, Quentame commented on src/meteofrance/client.py
> +                depth = 1, you wil have in addtion the buletin for all metropolitan
```suggestion
                depth = 1, you will have in addition, the bulletin for all metropolitan
```

2020-10-11 13:51 UTC, Quentame commented on src/meteofrance/client.py
>          coastal bulletin merged.
```suggestion
```

2020-10-11 13:51 UTC, Quentame commented on src/meteofrance/helpers.py
> +        list_phenomenoms: Dictionnary with phenomnom ID and color code of status.
```suggestion
        list_phenomenoms: Dictionary with phenomenon ID and color code of status.
```

2020-10-11 13:51 UTC, Quentame commented on src/meteofrance/helpers.py
>      # Init empty dictionnary
```suggestion
        Dictionary with keys and value human readable.
    """
    # Init empty dictionary
```

In more places ?

2020-10-11 13:51 UTC, Quentame commented on src/meteofrance/helpers.py
> +    are generaly sorted, but lot of cases identified where the order is inconsistent
```suggestion
    are generally sorted, but lot of cases identified where the order is inconsistent
```

2020-10-11 13:51 UTC, Quentame commented on src/meteofrance/model/forecast.py
> +            forecast (rain, snwow, freezing) for next 10 days.
```suggestion
            forecast (rain, snow, freezing) for next 10 days.
```

2020-10-11 13:51 UTC, Quentame commented on src/meteofrance/model/place.py
> +        admin2: A string correponding to an administrative code ( 'Département' number
```suggestion
        admin2: A string correponding to an administrative code ('Département' number
```

2020-10-11 13:51 UTC, Quentame commented on src/meteofrance/model/place.py
> +            country and amdin area  of the location.
```suggestion
            country and admin area of the location.
```

2020-10-11 13:51 UTC, Quentame commented on src/meteofrance/model/rain.py
> +        position: A dictionary with metadata about the position of the forecast place.
```suggestion
        updated_on:  A timestamp as int corresponding to the latest update date.
```

2020-10-11 13:51 UTC, Quentame commented on src/meteofrance/model/warning.py
> +            An integer correspondingt to the status code representing the maximul alert.
```suggestion
            An integer corresponding to the status code representing the maximum alert.
```

2020-10-11 13:51 UTC, Quentame commented on src/meteofrance/model/warning.py
> +        color_max: An integer reprenting the maximum alert level in the domain.
```suggestion
        color_max: An integer representing the maximum alert level in the domain.
```

2020-10-11 13:51 UTC, Quentame commented on src/meteofrance/model/warning.py
> +        """Merge the classical phenomenoms bulleting with the coastal one.
```suggestion
        """Merge the classical phenomenon bulletin with the coastal one.
```

2020-10-11 18:25 UTC, oncleben31 commented on README.rst
> +Descritption
Done

2020-10-11 18:37 UTC, oncleben31 commented
All comment implemented. A big thank you @Quentame

2020-10-11 20:10 UTC, oncleben31 commented
PR rebased with master. All comments implemented. All checks OK. LGTM

2020-10-11 20:15 UTC, merged